//! A byte-exact port of CPython's `random.Random` for the two operations the
//! reservoir sampler actually uses: seeding from an integer, and
//! `randint(0, n - 1)`.
//!
//! Why this exists
//! ---------------
//! `preprocess_lichess.py` selects its 30,000 games with Algorithm R driven by
//! `random.Random(seed)`. Reproducing "the same 30,000 games in the same slot
//! order" therefore means reproducing CPython's Mersenne Twister exactly, down
//! to the rejection-sampling loop inside `_randbelow`. An approximation, or any
//! other MT19937 variant, silently produces a *different but equally valid
//! looking* sample, which is the worst possible failure mode here: the corpus
//! archives are deleted after processing.
//!
//! Three CPython details are easy to get wrong and are each load-bearing:
//!
//! 1. Seeding is `init_by_array` over the seed's absolute value split into
//!    32-bit little-endian words (`_randommodule.c: random_seed`), NOT the
//!    plain `init_genrand` that most MT19937 implementations expose.
//! 2. `getrandbits(k)` for `k <= 32` is `genrand_uint32() >> (32 - k)`. It
//!    consumes exactly one 32-bit word. Implementations that mask instead of
//!    shifting take the wrong bits.
//! 3. `randint(0, n-1)` is `_randbelow(n)`, which is *rejection sampling*:
//!    draw `getrandbits(n.bit_length())` and redraw while `r >= n`. The redraws
//!    consume extra words, so any off-by-one in `bit_length` desynchronises the
//!    whole downstream stream, not just one draw.
//!
//! Verified against CPython in `tests/py_random.rs` using vectors generated by
//! the interpreter itself (`tests/py_random_vectors.json`).

const N: usize = 624;
const M: usize = 397;
const MATRIX_A: u32 = 0x9908_b0df;
const UPPER_MASK: u32 = 0x8000_0000;
const LOWER_MASK: u32 = 0x7fff_ffff;

pub struct PyRandom {
    mt: [u32; N],
    mti: usize,
}

impl PyRandom {
    /// Mirrors `random.Random(seed)` for a non-negative integer seed.
    ///
    /// CPython takes `abs(seed)` and splits it into 32-bit little-endian words;
    /// a zero seed still yields a one-word key of `[0]` (`keyused = 1` when
    /// `bits == 0`).
    pub fn new(seed: u64) -> Self {
        let bits = if seed == 0 { 0 } else { 64 - seed.leading_zeros() };
        let keyused = if bits == 0 { 1 } else { ((bits - 1) / 32 + 1) as usize };
        let mut key = [0u32; 2];
        key[0] = (seed & 0xffff_ffff) as u32;
        key[1] = (seed >> 32) as u32;

        let mut r = PyRandom { mt: [0u32; N], mti: N + 1 };
        r.init_by_array(&key[..keyused]);
        r
    }

    fn init_genrand(&mut self, s: u32) {
        self.mt[0] = s;
        for i in 1..N {
            let prev = self.mt[i - 1];
            self.mt[i] = 1812433253u32
                .wrapping_mul(prev ^ (prev >> 30))
                .wrapping_add(i as u32);
        }
        self.mti = N;
    }

    fn init_by_array(&mut self, key: &[u32]) {
        self.init_genrand(19650218);
        let mut i: usize = 1;
        let mut j: usize = 0;
        let mut k: usize = if N > key.len() { N } else { key.len() };
        while k > 0 {
            let prev = self.mt[i - 1];
            self.mt[i] = (self.mt[i] ^ ((prev ^ (prev >> 30)).wrapping_mul(1664525)))
                .wrapping_add(key[j])
                .wrapping_add(j as u32);
            i += 1;
            j += 1;
            if i >= N {
                self.mt[0] = self.mt[N - 1];
                i = 1;
            }
            if j >= key.len() {
                j = 0;
            }
            k -= 1;
        }
        k = N - 1;
        while k > 0 {
            let prev = self.mt[i - 1];
            self.mt[i] = (self.mt[i] ^ ((prev ^ (prev >> 30)).wrapping_mul(1566083941)))
                .wrapping_sub(i as u32);
            i += 1;
            if i >= N {
                self.mt[0] = self.mt[N - 1];
                i = 1;
            }
            k -= 1;
        }
        self.mt[0] = 0x8000_0000;
    }

    fn genrand_uint32(&mut self) -> u32 {
        if self.mti >= N {
            for kk in 0..(N - M) {
                let y = (self.mt[kk] & UPPER_MASK) | (self.mt[kk + 1] & LOWER_MASK);
                self.mt[kk] = self.mt[kk + M] ^ (y >> 1) ^ (if y & 1 != 0 { MATRIX_A } else { 0 });
            }
            for kk in (N - M)..(N - 1) {
                let y = (self.mt[kk] & UPPER_MASK) | (self.mt[kk + 1] & LOWER_MASK);
                self.mt[kk] =
                    self.mt[kk + M - N] ^ (y >> 1) ^ (if y & 1 != 0 { MATRIX_A } else { 0 });
            }
            let y = (self.mt[N - 1] & UPPER_MASK) | (self.mt[0] & LOWER_MASK);
            self.mt[N - 1] = self.mt[M - 1] ^ (y >> 1) ^ (if y & 1 != 0 { MATRIX_A } else { 0 });
            self.mti = 0;
        }

        let mut y = self.mt[self.mti];
        self.mti += 1;
        y ^= y >> 11;
        y ^= (y << 7) & 0x9d2c_5680;
        y ^= (y << 15) & 0xefc6_0000;
        y ^= y >> 18;
        y
    }

    /// `random.getrandbits(k)` for `0 <= k <= 64`.
    ///
    /// The `k <= 32` fast path is the only one the reservoir sampler reaches
    /// (a month's `eligible` count never approaches 2^32), but the wide path is
    /// implemented too so the CPython-equivalence tests can exercise it: a port
    /// that is only correct on the path we happen to use is a port nobody can
    /// safely reuse.
    pub fn getrandbits(&mut self, k: u32) -> u64 {
        assert!(k <= 64, "getrandbits: k={k} exceeds this port's 64-bit limit");
        if k == 0 {
            return 0;
        }
        if k <= 32 {
            return (self.genrand_uint32() >> (32 - k)) as u64;
        }
        // CPython fills 32-bit words least-significant first on little-endian
        // hosts, shifting only the final (most significant) partial word.
        let words = ((k - 1) / 32 + 1) as usize;
        let mut out: u64 = 0;
        let mut rem = k as i64;
        for i in 0..words {
            let mut r = self.genrand_uint32();
            if rem < 32 {
                r >>= 32 - rem as u32;
            }
            out |= (r as u64) << (32 * i);
            rem -= 32;
        }
        out
    }

    /// `random.Random._randbelow_with_getrandbits(n)`: uniform on `[0, n)` via
    /// rejection sampling. Returns 0 for `n == 0`, matching CPython.
    pub fn randbelow(&mut self, n: u64) -> u64 {
        if n == 0 {
            return 0;
        }
        let k = 64 - n.leading_zeros(); // n.bit_length()
        loop {
            let r = self.getrandbits(k);
            if r < n {
                return r;
            }
        }
    }

    /// `random.randint(0, n - 1)`, i.e. `randrange(0, n)` -> `_randbelow(n)`.
    /// This is the single call `preprocess_lichess.py:152` makes.
    #[inline]
    pub fn randint_below(&mut self, n: u64) -> u64 {
        self.randbelow(n)
    }
}
