//! Proves the Rust port reproduces CPython's `random.Random` exactly.
//!
//! The vectors in `py_random_vectors.txt` are generated by the interpreter
//! itself (`analysis/scripts/gen_py_random_vectors.py`), so this is a
//! comparison against real CPython output, not against a second reading of the
//! same spec. Regenerate them if the reference Python version ever changes;
//! MT19937 and `_randbelow` have been stable since 3.2, but the test is cheap
//! insurance against that assumption silently expiring.

use std::collections::HashMap;

use clkscan::pyrandom::PyRandom;
use clkscan::reservoir::Reservoir;

fn vectors() -> HashMap<String, Vec<u64>> {
    let raw = include_str!("py_random_vectors.txt");
    raw.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|line| {
            let mut it = line.split_whitespace();
            let name = it.next().expect("record name").to_string();
            let vals = it
                .map(|v| v.parse::<u64>().unwrap_or_else(|e| panic!("{name}: bad value {v:?}: {e}")))
                .collect();
            (name, vals)
        })
        .collect()
}

/// The synthetic eligibility bitstream the Python generator used. Kept in sync
/// by construction: both sides compute it from the same closed form.
fn synthetic_bits(len: usize) -> Vec<bool> {
    (0..len)
        .map(|i| (i as u64).wrapping_mul(2654435761) % 1000 < 70)
        .collect()
}

#[test]
fn genrand_uint32_stream_matches_cpython() {
    let v = vectors();
    let expected = &v["seed42_getrandbits32"];
    let mut r = PyRandom::new(42);
    for (i, want) in expected.iter().enumerate() {
        let got = r.getrandbits(32);
        assert_eq!(got, *want, "getrandbits(32) diverged at draw {i}");
    }
}

#[test]
fn getrandbits_matches_cpython_across_widths_and_seeds() {
    let v = vectors();
    let widths: Vec<u32> = v["widths"].iter().map(|w| *w as u32).collect();
    for seed in [0u64, 1, 42, 12345, 1 << 31, 1 << 32, u64::MAX] {
        let expected = &v[&format!("mixed_{seed}")];
        let mut r = PyRandom::new(seed);
        for (i, (k, want)) in widths.iter().zip(expected.iter()).enumerate() {
            let got = r.getrandbits(*k);
            assert_eq!(got, *want, "seed {seed}: getrandbits({k}) diverged at draw {i}");
        }
    }
}

/// The call the reservoir sampler actually makes. Rejection sampling inside
/// `_randbelow` means a single mismatch here desynchronises everything after
/// it, so this walks 3000 consecutive draws rather than spot-checking.
#[test]
fn randint_below_matches_cpython() {
    let v = vectors();

    let mut r = PyRandom::new(42);
    for (i, want) in v["randint_reservoir_42"].iter().enumerate() {
        let n = 30001 + i as u64;
        assert_eq!(r.randint_below(n), *want, "randint(0, {}) diverged at draw {i}", n - 1);
    }

    // Small n exercises the narrow bit widths and the rejection loop hardest.
    let mut r = PyRandom::new(42);
    for (i, want) in v["randint_small_42"].iter().enumerate() {
        let n = 1 + i as u64;
        assert_eq!(r.randint_below(n), *want, "randint(0, {}) diverged at draw {i}", n - 1);
    }
}

/// End-to-end: the same eligibility bitstream through both implementations of
/// Algorithm R must produce identical reservoirs, in identical slot order.
#[test]
fn algorithm_r_reproduces_cpython_reservoir() {
    let v = vectors();
    let len = v["algoR_stream_len"][0] as usize;
    let bits = synthetic_bits(len);

    let eligible_total = bits.iter().filter(|b| **b).count() as u64;
    assert_eq!(
        eligible_total, v["algoR_stream_eligible"][0],
        "the Rust and Python synthetic bitstreams disagree, so the rest of this \
         test would be comparing different inputs"
    );

    for (max_games, seed) in [(1000usize, 42u64), (1000, 7), (30000, 42), (137, 99)] {
        let mut res: Reservoir<u64> = Reservoir::new(max_games, seed);
        for (ordinal, eligible) in bits.iter().enumerate() {
            if *eligible {
                res.offer(ordinal as u64);
            }
        }
        let got = res.into_slots();
        let want = &v[&format!("algoR_{max_games}_{seed}")];
        assert_eq!(
            got.len(),
            want.len(),
            "max_games={max_games} seed={seed}: reservoir size differs"
        );
        for (slot, (g, w)) in got.iter().zip(want.iter()).enumerate() {
            assert_eq!(
                g, w,
                "max_games={max_games} seed={seed}: slot {slot} holds game ordinal {g}, \
                 CPython put ordinal {w} there"
            );
        }
    }
}
