"""Build the side-by-side results table for the extra anomaly arms from
whatever <root>/<arm>/results.json files exist. Safe to re-run at any time;
arms that are missing, running or failed are listed as such, never dropped.

  python aggregate_extra_arms.py --root ~/Bacsain/thesis2/analysis/extra_arms \
      --out_json analysis/anomaly-extra-arms-results.json \
      --out_md analysis/anomaly-extra-arms-results.md

Plan: analysis/anomaly-extra-arms-plan.md. Descriptive only: 0.80 is shown as
a reference level, never as a target or criterion.
"""
import argparse
import json
import os
import time

ARMS = ["A0", "A0g", "A1", "A2", "A2g", "A3_seed0", "A3_seed1", "A3g_seed0", "A4"]
HEAD = [("seen", "Seen"), ("withheld_band", "Withheld bands"),
        ("withheld_rate_vs_clean", "Withheld rate vs clean"), ("withheld_both", "Both withheld")]
EXTRA = [("withheld_band_rate02_vs_clean", "WB 2%"), ("withheld_band_rate05_vs_clean", "WB 5%"),
         ("withheld_both_vs_clean", "Both vs clean")]
REF_PUBLISHED = {"seen": 0.807, "withheld_band": 0.685, "withheld_rate_vs_clean": 0.685, "withheld_both": 0.629}


def status(root, arm):
    d = os.path.join(root, arm)
    if os.path.exists(os.path.join(d, "DONE")):
        return "done"
    if os.path.exists(os.path.join(d, "FAILED")):
        return "failed"
    if os.path.exists(os.path.join(d, "STARTED")):
        return "running (or died without a marker; check its log)"
    return "not started"


def fmt(r, key="auc"):
    if not r or r.get(key) is None:
        return "n/a"
    s = f"{r[key]:.3f}"
    if r.get("ci95"):
        s += f" [{r['ci95'][0]:.3f}, {r['ci95'][1]:.3f}]"
    return s


def fmt_diff(r):
    if not r or r.get("diff_vs_A0") is None:
        return "n/a"
    c = r["diff_vs_A0_ci95"]
    return f"{r['diff_vs_A0']:+.3f} [{c[0]:+.3f}, {c[1]:+.3f}]"


def game_rows(res):
    """-> list of (row label, game_level_report dict)"""
    rows = []
    for arm, r in res.items():
        if r is None:
            continue
        if arm == "A0":
            rows.append(("S_att (computed score)", r.get("S_att")))
        if "variants" in r:
            for v, rep in r["variants"].items():
                rows.append((v, rep))
        elif "game_level" in r:
            rows.append((arm, r["game_level"]))
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=os.path.expanduser("~/Bacsain/thesis2/analysis/extra_arms"))
    ap.add_argument("--out_json", default="anomaly-extra-arms-results.json")
    ap.add_argument("--out_md", default="anomaly-extra-arms-results.md")
    a = ap.parse_args()

    res, st = {}, {}
    for arm in ARMS:
        st[arm] = status(a.root, arm)
        p = os.path.join(a.root, arm, "results.json")
        res[arm] = json.load(open(p)) if (st[arm] == "done" and os.path.exists(p)) else None
    cache = os.path.join(a.root, "A4_cache", "CACHE_DONE")
    st["A4_cache"] = "done" if os.path.exists(cache) else "not done"

    L = []
    L.append("# Anomaly detection: extra arms, results")
    L.append("")
    L.append(f"Generated by `analysis/scripts/aggregate_extra_arms.py` on {time.strftime('%Y-%m-%d %H:%M %z')} "
             f"from `{a.root}`. Pre-registered plan: `analysis/anomaly-extra-arms-plan.md`. Every arm in the "
             "plan is listed below whatever its state or outcome.")
    L.append("")
    L.append("## Arm status")
    L.append("")
    L.append("| Arm | Status |")
    L.append("|---|---|")
    for k, v in st.items():
        L.append(f"| {k} | {v} |")
    L.append("")
    a0 = res.get("A0")
    if a0 and a0.get("gate"):
        g = a0["gate"]
        L.append(f"A0 reproduction gate: {'PASS' if g['pass'] else 'FAIL'} "
                 f"(seen {g['reproduced']['seen']:.4f} vs {g['reference']['seen']:.4f}; withheld bands "
                 f"{g['reproduced']['withheld_band']:.4f} vs {g['reference']['withheld_band']:.4f}; tolerance {g['tolerance']}).")
        L.append("")

    rows = game_rows(res)
    L.append("## Game-level ROC-AUC, side by side (95% bootstrap CI)")
    L.append("")
    L.append("\"Is this game substituted\". A0g, A2g and A3g use the grouped (twin-disjoint) split; their "
             "seen column is not on the same test games as the others.")
    L.append("")
    L.append("| Arm | " + " | ".join(h for _, h in HEAD + EXTRA) + " | Strength check (hard-neg vs clean) |")
    L.append("|---|" + "---|" * (len(HEAD) + len(EXTRA) + 1))
    L.append("| Published v2 LightGBM | " + " | ".join(f"{REF_PUBLISHED[k]:.3f}" for k, _ in HEAD)
             + " | 0.530 | 0.558 | n/a | n/a |")
    L.append("| Reference level (not a target) | " + " | ".join("0.800" for _ in HEAD + EXTRA) + " | n/a |")
    for label, rep in rows:
        if not rep:
            continue
        c = rep.get("conditions", {})
        L.append(f"| {label} | " + " | ".join(fmt(c.get(k)) for k, _ in HEAD + EXTRA)
                 + f" | {fmt(rep.get('strength_check'))} |")
    L.append("")

    L.append("## Difference against A0 on the same games (paired bootstrap, 95% CI)")
    L.append("")
    L.append("| Arm | " + " | ".join(h for _, h in HEAD + EXTRA) + " |")
    L.append("|---|" + "---|" * (len(HEAD) + len(EXTRA)))
    for label, rep in rows:
        if not rep or label in ("A0",):
            continue
        c = rep.get("conditions", {})
        if not any((c.get(k) or {}).get("diff_vs_A0") is not None for k, _ in HEAD):
            continue
        L.append(f"| {label} | " + " | ".join(fmt_diff(c.get(k)) for k, _ in HEAD + EXTRA) + " |")
    L.append("")

    L.append("## Precision, TPR and realized FPR at validation-chosen thresholds")
    L.append("")
    L.append("Thresholds are quantiles of each arm's scores on clean validation games. The corpus is "
             "positive-heavy, so precision is not a deployment figure.")
    L.append("")
    L.append("| Arm | Condition | P@1%FPR | TPR@1% | FPR realized | P@5%FPR | TPR@5% | FPR realized |")
    L.append("|---|---|---|---|---|---|---|---|")
    for label, rep in rows:
        if not rep:
            continue
        for k, h in HEAD:
            r = rep.get("conditions", {}).get(k)
            if not r:
                continue
            p1 = r["precision_at_fpr"]["0.01"]; p5 = r["precision_at_fpr"]["0.05"]
            f = lambda x: "n/a" if x is None else f"{x:.3f}"  # noqa: E731
            L.append(f"| {label} | {h} | {f(p1['precision'])} | {f(p1['tpr'])} | {f(p1['realized_fpr'])} | "
                     f"{f(p5['precision'])} | {f(p5['tpr'])} | {f(p5['realized_fpr'])} |")
    L.append("")

    L.append("## Move-level localization (substituted games; candidates = suspect plies from ply 16)")
    L.append("")
    L.append("| Arm | Score | Condition | hit@1 | random | prec@3 | prec@5 | random | ply AUC | Engine-proximity AUC (top1 match, clean plies) |")
    L.append("|---|---|---|---|---|---|---|---|---|---|")
    locs = []
    if a0 and a0.get("S_att_localization"):
        locs.append(("S_att", "alpha x d", a0["S_att_localization"]))
    for arm in ("A3_seed0", "A3_seed1", "A3g_seed0", "A4"):
        r = res.get(arm)
        if r:
            locs.append((arm, "instance logit", r.get("localization_instance_logit")))
            locs.append((arm, "attention", r.get("localization_attention")))
    for arm, sc, rep in locs:
        if not rep:
            continue
        ep = rep.get("engine_proximity")
        eps = f"{ep['auc_top1_match']:.3f} (n={ep['n_plies']})" if ep else "n/a"
        for k in ("seen", "withheld_band", "withheld_rate", "withheld_both",
                  "withheld_band_rate02_vs_clean", "withheld_band_rate05_vs_clean"):
            r = rep.get(k)
            if not r:
                continue
            L.append(f"| {arm} | {sc} | {k} | {r['hit1']:.3f} | {r['rand_hit1']:.3f} | {r['p3']:.3f} | "
                     f"{r['p5']:.3f} | {r['rand_p5']:.3f} | {r['ply_auc']:.3f} | {eps} |")
    L.append("")

    a1 = res.get("A1")
    L.append("## A1 player-level AUC (a different question: is this PLAYER cheating)")
    L.append("")
    if a1:
        L.append("| Condition | Score | Agg | k=1 | k=5 | k=10 | k=20 |")
        L.append("|---|---|---|---|---|---|---|")
        for cname, cd in a1["conditions"].items():
            for sname, sd in cd.items():
                for agg in ("mean", "max"):
                    cells = []
                    for k in ("1", "5", "10", "20"):
                        r = sd.get(k, {}).get(agg)
                        cells.append(fmt(r) if r else "n/a")
                    L.append(f"| {cname} | {sname} | {agg} | " + " | ".join(cells) + " |")
    else:
        L.append(f"A1 status: {st['A1']}.")
    L.append("")

    L.append("## A3 validation-only tuning")
    L.append("")
    for arm in ("A3_seed0", "A3g_seed0"):
        r = res.get(arm)
        if r:
            L.append(f"- {arm}: chosen hidden={r['chosen_config']['hidden']}, dropout={r['chosen_config']['dropout']}, "
                     f"best val AUC {r['best_val_auc']:.4f} (full log in `{arm}/tuning_log.json`).")
    L.append("")

    L.append("## Deviations from the plan")
    L.append("")
    any_dev = False
    for arm, r in res.items():
        for dv in (r or {}).get("deviations", []):
            L.append(f"- {arm}: {dv}"); any_dev = True
    if not any_dev:
        L.append("- None recorded by the arm scripts. Check the plan's section 9 for manual entries.")
    L.append("")

    L.append("## Plain-language takeaways")
    L.append("")
    L.append("Auto-generated descriptive lines; a human should rewrite this section after reading the tables.")
    L.append("")
    for label, rep in rows:
        if not rep:
            continue
        c = rep.get("conditions", {})
        if c.get("seen") and c.get("withheld_band"):
            L.append(f"- {label}: seen {c['seen']['auc']:.3f}, withheld bands {c['withheld_band']['auc']:.3f}"
                     + (f" (difference against A0 there {c['withheld_band']['diff_vs_A0']:+.3f})"
                        if c['withheld_band'].get('diff_vs_A0') is not None else "") + ".")
    L.append("")

    with open(a.out_md, "w") as f:
        f.write("\n".join(L) + "\n")
    with open(a.out_json, "w") as f:
        json.dump({"generated": time.strftime("%Y-%m-%d %H:%M:%S %z"), "root": a.root, "status": st,
                   "arms": res}, f, indent=1)
    print(f"wrote {a.out_md} and {a.out_json}")


if __name__ == "__main__":
    main()
